### ISSUE TITLE
Running with non-root user results in permission issues

### ISSUE THREAD

**Issue by asgrim** [rockmagic/sencha-cmd#1]
When we run with `-u $(id -u):$(id -g)` set, we get this error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/root/bin/Sencha/Cmd/sencha\": stat /root/bin/Sencha/Cmd/sencha: permission denied": unknown.
```

Looks like this container has to be run by `root`, but when we do that, the built artefacts are created with the `root` user, so we get permission issues elsewhere.

A workaround is to `chown` the generated build after being created, but that doesn't seem optimal?

Any suggestions would be welcome, or maybe this could be fixed in the container to not require to be run as root perhaps?

**Comment by rockmagic** [comment]
The problem is about sencha-cmd installation path being under /root directory, which is not accessible by other users.
Installation directory now fixed to /opt/Sencha/Cmd, this should help. Pull the latest image to update.
Note that `latest` now is`6.6.0`, explicitly specify image tag if you need `6.5.3` or other version.

**Comment by asgrim** [comment]
Thanks!
